### ISSUE TITLE
External Eval Error following guide

### ISSUE THREAD

**Issue by DHuryn** [minio/spark-select#12]
When following the guide for scala (spark), we get an external eval error. We use the file provided in the examples folder, and everything works up until df.select.

`com.amazonaws.services.s3.model.AmazonS3Exception: The query cannot be evaluated. Please check the query and file and try again. (Service: Amazon S3; Status Code: 400; Error Code: ExternalEvalException;`

As best we can tell, it is treating the integers of the age column as strings, because when we manually run the same sql query on the bucket in the aws console, it gives us the same error, but when we cast age to an int, it works.

**Comment by harshavardhana** [comment]
> As best we can tell, it is treating the integers of the age column as strings, because when we manually run the same sql query on the bucket in the aws console, it gives us the same error, but when we cast age to an int, it works.

This is because AWS doesn't support auto casting from string to integers like MinIO so we never really bothered to fix that for AWS. 

We think that this is a bug and limitation of AWS as it should make the S3 Select API more consumable than what it really is. I am not sure there is a good reason to address this. 

For AWS you should their own EMR based s3select implementation https://docs.aws.amazon.com/emr/latest/ReleaseGuide/emr-spark-s3select.html
