### ISSUE TITLE
Is it possible to support Spark Delta Lake

### ISSUE THREAD

**Issue by tobegit3hub** [minio/spark-select#9]
Now spark-select has supported minioSelectCSV, minioSelectJSON and minioSelectParquet so we can read and write files from MinIO. Spark Delta Lake is based on parquet but has more metadata files and need new Source/Sink to read.

I'm not sure if it is possible for MinIO to support Delta Lake with minimal effort.

**Comment by harshavardhana** [comment]
This project is meant for spark data source - if they don't support spark data sources it won't work. If they do then it automatically work without any changes.

I am not sure if we have any current cycles to evaluate spark Delta lake, feel free to test it and let us know. We are curious to hear how it turns out.

Please join our https://slack.min.io if you want to discuss further.

**Comment by tobegit3hub** [comment]
Thanks @harshavardhana for replying. Actually, [Delta Lake])(https://github.com/delta-io/delta) is another data sources for Spark. It is kinds of different from parquet and we use it like these.

```
df.write.format("delta").save("/tmp/delta-table")

spark.read.format("delta").load("hdfs:///delta_lake/data/")
```

This project has provided `minioSelectParquet` which make it possible to read or write parquet files in MinIO like this.

```
spark.read.format("minioSelectParquet").load("s3://path/to/my/datafiles")
```

And I think we need to implement another class to support Delta Lake. It's import for Delta Lake users because we may use batch or streaming Spark jobs to read and write data at the same time.
